ASoC: Intel: avs: Fix build error due to missing header file include
Kernel build fails with error:
implicit declaration of function 'parse_int_array_user' due to missing
header include. Added "#include <linux/string_helpers.h> to fix the
build issue.

Signed-off-by: Jeevaka Prabu Badrappan <jeevaka.badrappan@intel.com>